# Generated by Django 2.2.3 on 2019-07-12 13:16

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [CreateExtension("postgis")]
