# Generated by Django 2.2.3 on 2019-07-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("robbit", "0002_area_image_tile")]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="robbit.Tile",
            ),
        )
    ]
