# Generated by Django 2.2.3 on 2019-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("robbit", "0005_image_faves")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="faves",
            field=models.PositiveIntegerField(db_index=True),
        )
    ]
