# Generated by Django 2.2.3 on 2020-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("robbit", "0006_auto_20190718_1221")]

    operations = [
        migrations.AlterField(
            model_name="tile", name="x", field=models.BigIntegerField(db_index=True)
        ),
        migrations.AlterField(
            model_name="tile", name="y", field=models.BigIntegerField(db_index=True)
        ),
    ]
